### ISSUE TITLE
请问如何发送图片消息

### ISSUE THREAD

**Issue by w1ndseeker** [RF-Tar-Railt/satori-python#1]
使用
```
img_msg =Message(content=Image.of(path=img_path))
```
构造的消息使用account 的send \ send_message \ message_create都无法发送
请问发送图片该如何操作

**Comment by RF-Tar-Railt** [comment]
日志呢

**Comment by RF-Tar-Railt** [comment]
还有你用的什么操作系统，用的多少版本的Python，对接的平台是什么

**Comment by w1ndseeker** [comment]
使用
```
img = Image.of(path="/root/test_img/00198-980786390.png")
message = Message(content=[img])
await account.send(event, [message])
```
报错
```
send_message msg: <message ><img src="file:///root/test_img/00198-980786390.png" cache="None" timeout="None" width="None" height="None" /></message>
Task exception was never retrieved
future: <Task finished name='Task-23' coro=<WsNetwork.message_handle.<locals>.event_parse_task() done, defined at miniconda3/envs/ws/lib/python3.10/site-packages/satori/network/ws_client.py:52> exception=ApiNotImplementedException('500 internal server error')>
Traceback (most recent call last):
  File "miniconda3/envs/ws/lib/python3.10/site-packages/satori/network/ws_client.py", line 58, in event_parse_task
    await self.app.post(event)
  File "miniconda3/envs/ws/lib/python3.10/site-packages/satori/client.py", line 66, in post
    await asyncio.gather(*(callback(account, event) for callback in self.event_callbacks))
  File "dev/test_satori.py", line 169, in on_message
    await account.send(event, [message])
  File "miniconda3/envs/ws/lib/python3.10/site-packages/satori/account.py", line 36, in send
    return await self.send_message(event.channel.id, message)
  File "miniconda3/envs/ws/lib/python3.10/site-packages/satori/account.py", line 51, in send_message
    return await self.message_create(channel_id=channel_id, content=msg)
  File "miniconda3/envs/ws/lib/python3.10/site-packages/satori/account.py", line 93, in message_create
    res = await self.client.call_http(
  File "miniconda3/envs/ws/lib/python3.10/site-packages/satori/network/base.py", line 76, in call_http
    raise ApiNotImplementedException(await resp.text())
satori.exception.ApiNotImplementedException: 500 internal server error
```

环境是linux+chronocat+py310

是用法不对吗 能否给一个发送图片的样例

**Comment by w1ndseeker** [comment]
还是报未实现错误，可能是chronocat satori对应的部分没实现？ 我换一个别的平台bot测试一下

**Comment by ilharp** [comment]
Chronocat 只有最新版本支持了发送媒体；此外推荐使用 Linux QQ 或 Docker 发送，据说在 Windows 高版本 QQ 上发送会有问题。你使用的 Chronocat 是最新版本吗？

**Comment by w1ndseeker** [comment]
> Chronocat 只有最新版本支持了发送媒体；此外推荐使用 Linux QQ 或 Docker 发送，据说在 Windows 高版本 QQ 上发送会有问题。你使用的 Chronocat 是最新版本吗？

使用的是0.0.54版本的第三方windowsqq的镜像

**Comment by w1ndseeker** [comment]
> Chronocat 只有最新版本支持了发送媒体；此外推荐使用 Linux QQ 或 Docker 发送，据说在 Windows 高版本 QQ 上发送会有问题。你使用的 Chronocat 是最新版本吗？

替换成linux版本的以后可以了 谢谢
